### ISSUE TITLE
Server error while client beginning connect 

### ISSUE THREAD

**Issue by phihung93ap** [sourcey/symple-server-node#4]
![untitled](https://cloud.githubusercontent.com/assets/5515852/5725456/85bcb77c-9b85-11e4-9d99-f2d7482a852f.png)
Can anyone help me ?

**Comment by auscaster** [comment]
Please post your config.json file. If you're not using anonymous mode then a token must be provided with the initial request.

**Comment by phihung93ap** [comment]
Here is my config.json file

{
  /* The ID of the node instance */
  "nodeId" : 1,

  /* The port to listen on */
  "port" : 4500,  

  /* Allow anonymous connections */
  "anonymous" : false,  

  /* Redis configuration (required if anonymous == false) */
  "redis" : {
    "host" : "127.0.0.1",
    "port" : 6379,
    "password" : ""
  },

  /* SSL configuration (required if using HTTPS) */
  "ssl" : {
    "enabled" : false,
    "key" : "/path/to/.key",
    "cert" : "/path/to/.crt"
  }
}

**Comment by auscaster** [comment]
Please set anonymous to true if you're not sending authentication tokens to the server. Otherwise, please send a token with the initial announce request.

**Comment by phihung93ap** [comment]
It's working , thanks you !

**Comment by auscaster** [comment]
Great! Please close the issue if all is working.
