### ISSUE TITLE
http://symple.sourcey.com/ not working

### ISSUE THREAD

**Issue by MichalGallovic** [sourcey/symple-server-node#5]
Hello,

the Media streaming [demo](http://symple.sourcey.com/ ) is not working, responding with `Internal Server Error`

**Comment by auscaster** [comment]
Hello Michal

You can download the entire demo code ([here](https://github.com/sourcey/symple-client) and [here](https://github.com/sourcey/symple-client/tree/master/demo)) and run it locally - it's very easy to setup! I'm on holidays over the weekend and will check back with your progress on Monday.

**Comment by MichalGallovic** [comment]
I will check on that on Tuesday, going on holiday as well, thank you!

**Comment by auscaster** [comment]
The server at http://symple.sourcey.com is back up now :)

**Comment by MichalGallovic** [comment]
:+1 Thank you very much ! will check on that on Tuesday
